# Generated by Django 3.2.8 on 2021-11-23 11:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='type of file')),
                ('file', models.ImageField(upload_to=products.models.get_path_file)),
                ('size', models.IntegerField(default=0, verbose_name='size of file')),
                ('name', models.CharField(max_length=255, verbose_name='name of file')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name of product')),
            ],
            options={
                'verbose_name': 'type of product',
                'verbose_name_plural': 'type of products',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='name of product')),
                ('description', models.TextField(verbose_name='name of description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='price of product')),
                ('year', models.IntegerField(db_index=True, verbose_name='year of product release')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.file', verbose_name='product photo')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producttype')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'unique_together': {('type', 'file')},
            },
        ),
    ]
