# Generated by Django 3.2.8 on 2021-11-27 21:40

from django.db import migrations, models
import django.db.models.deletion


def forwards_add_table(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductFile = apps.get_model("products", "ProductFile")

    product_qs = Product.objects.filter(image__isnull=False)

    for product in product_qs:
        ProductFile.objects.create(file_ptr=product.image,
                                   type=product.image.type,
                                   image=product.image.image,
                                   size=product.image.size,
                                   name=product.image.name,
                                   product_id=product.id)


def reset_delete_table(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductFile = apps.get_model("products", "ProductFile")

    product_file_qs = ProductFile.objects.all()
    for product_file in product_file_qs:
        Product.objects.filter(id=product_file.product_id).update(image=product_file.file_ptr)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.file')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_file', to='products.product')),
            ],
            bases=('products.file',),
        ),
        migrations.RunPython(forwards_add_table, reset_delete_table),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
