# Generated by Django 3.2.8 on 2021-12-07 10:53

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/static/', location='/home/vadim/WIS/backend/line_story/line/staticfiles'), upload_to=products.models.get_path_file, validators=[products.models.validate_image]),
        ),
    ]
