# Generated by Django 3.2.8 on 2021-12-07 11:05

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_file_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='image',
            field=models.ImageField(upload_to=products.models.get_path_file, validators=[products.models.validate_image]),
        ),
    ]
