# Generated by Django 3.2.8 on 2021-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211216_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_reserved',
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
