# Generated by Django 3.2.8 on 2021-12-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211216_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
