# Generated by Django 3.2.8 on 2021-10-26 10:56

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/image_profile/default.png', upload_to=users.models._user_directory_path, verbose_name='Фото профиля'),
        ),
    ]
