# Generated by Django 3.2.8 on 2021-11-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.OneToOneField(default='default image', on_delete=django.db.models.deletion.CASCADE, to='products.file', verbose_name='profile photo'),
            preserve_default=False,
        ),
    ]
