# Generated by Django 3.2.8 on 2021-10-31 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211031_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='phone number must not consist of space and requires country code. eg : +79546748973', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone'),
        ),
    ]
