# Generated by Django 3.2.8 on 2021-12-09 11:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_file_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'cart item', 'verbose_name_plural': 'carts items'},
        ),
    ]
