# Generated by Django 3.2.8 on 2021-12-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211209_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=1800, null=True, verbose_name='address'),
        ),
    ]
