# Generated by Django 3.2.8 on 2021-12-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(blank=True, max_length=1800, null=True, verbose_name='delivery address'),
        ),
    ]
